# Generated by Django 3.1.3 on 2021-04-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientpage', '0002_auto_20210427_0858'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listviewpdf',
            options={},
        ),
        migrations.AddField(
            model_name='listviewpdf',
            name='link',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
