# Generated by Django 3.1.3 on 2021-04-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientpage', '0004_remove_listviewpdf_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='listviewpdf',
            name='number_page',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
