# Generated by Django 3.1.3 on 2021-04-28 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientpage', '0005_listviewpdf_number_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='listviewpdf',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
