# Generated by Django 3.1.3 on 2021-04-28 02:55

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientpage', '0007_listviewpdf_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listviewpdf',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title'),
        ),
    ]
