# Generated by Django 3.1.3 on 2021-04-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='bio',
            new_name='infos_pdf',
        ),
        migrations.AddField(
            model_name='user',
            name='pdf_file',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
