# Generated by Django 3.1.3 on 2021-04-27 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210424_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pdf',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
