# Generated by Django 3.1.3 on 2021-04-27 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ifpaid',
            field=models.BooleanField(default='False'),
        ),
    ]
